[package]
name = "getset"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.9.8"
console = "0.16.1"
pty-process = "0.5.3"

[dev-dependencies]
assert_cmd = "2.1"
predicates = "3.1"
