[package]
name = "getset"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
indicatif = "0.18.3"
console = "0.16.1"
pty-process = "0.5.3"
