[[commands]]
title = "List files"
command = "ls -la"

[[commands]]
title = "Slow loop"
command = """
i=0

while [ $i -le 4 ]
do
  echo Number: $i
  sleep $i
  ((i++))
done
"""

[[commands]]
title = "Show date"
command = "date"
